class Locators_User:
    USER_MENU_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[2]/div[1]/nav[1]/div[2]/a[23]/span[2]"
    LANGUEGE_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/span[1]"
    KEBAB_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[1]/span[1]/i[1]"
    ADD_BUTTON_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]"
    EXPORT_BUTTON_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]"
    ADD_BY_BRAND_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[3]"
    IMPORT_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[4]"
    TAMPLET_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[5]"
    TEAM_TWO_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[16]/td[5]"
    FIRST_NAME_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[2]/span[1]/div[1]/input[1]"
    LAST_NAME_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[3]/span[1]/div[1]/input[1]"
    EMAIL_PATH = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[4]/span[1]/div[1]/input[1]"
    PHONE_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[5]/span[1]/div[1]/input[1]"
    ADITIONAL_PHONE_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[6]/span[1]/div[1]/input[1]"
    PASSWORD_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[7]/span[1]/div[1]/input[1]"
    #STOREIDS_FIELD_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[7]/span[1]/div[2]/input[1]"
    STORID_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[7]/span[1]/div[2]/input[1]"
    CITY_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[8]/div[1]/div[2]/span[1]/div[1]/input[1]"
    BUILDING_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[8]/div[1]/div[3]/span[1]/div[1]/input[1]"
    APARTMENT_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[8]/div[1]/div[4]/span[1]/div[1]/input[1]"
    FLOOR_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[8]/div[1]/div[5]/span[1]/div[1]/input[1]"
    COMMENT_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[8]/div[1]/div[6]/textarea[1]"
    ACCOUNTOWNER_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[9]/div[1]/div[1]/span[1]/div[1]/input[1]"
    ACCOUNTNUMBER_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[9]/div[1]/div[2]/span[1]/div[1]/input[1]"
    BRANCH_NUMBER_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[9]/div[1]/div[3]/span[1]/div[1]/input[1]"
    CREDICSACCOUNT_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[10]/span[1]/span[1]"
    INCOME_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[11]/div[1]/div[2]/span[1]/div[1]/input[1]"
    OUTCOME_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[11]/div[1]/div[3]/span[1]/div[1]/input[1]"
    USERID_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[12]/span[1]/div[1]/input[1]"
    MARKETINGLIST_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[13]/span[1]/span[1]"
    ETRADOAPROVED_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[14]/span[1]/span[1]"
    TAKANON_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[15]/span[1]/span[1]"
    UPDATE_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/input[1]"
    NEXT_PAGE_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]/span[5]/i[1]"
    ACTIVE_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[16]/span[1]/span[1]"
    BACKWARD_PAGE_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]/span[1]/i[1]"
    EMAIL_ERROR_XPATH = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[4]/div[1]"
    emu = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[4]/span[1]/div[1]/input[1]"
    USER_TITLE = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[4]/div[1]"
    CLOSE_BY_X_ICONE = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/span[1]/i[1]"
    ERROR_FIRST_PHONE_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[5]/div[1]"
    ERROR_FPHONE_NULL_XPTH = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[5]/div[1]"
    ERROR_FPHONE_WITHLETTER_XPTH = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[5]/div[1]"
    ETRADO_STRORE_ID_ERROR_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[7]/div[1]"
    GROUP2GMAIL_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[8]/td[3]"
    #################################################################################################

    # add users locator
    ADD_USER_ACTIVE_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[17]/span[1]/span[1]"
    ADD_USER_FNAME_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[2]/span[1]/div[1]/input[1]"
    ADD_USER_LNAME_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[3]/span[1]/div[1]/input[1]"
    ADD_USER_EMAIL_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[4]/span[1]/div[1]/input[1]"
    ADD_USER_PHONE_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[5]/span[1]/div[1]/input[1]"
    ADD_USER_PHONE2_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[6]/span[1]/div[1]/input[1]"
    ADD_USER_PASSWORD_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[7]/span[1]/div[1]/input[1]"
    ADD_USER_STORRRID_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[8]/span[1]/div[2]/input[1]"
    ADD_USER_CITY_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[9]/div[1]/div[1]/span[1]/div[1]/input[1]"
    ADD_USER_CREDICSACCOUNT_XPATH ="/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[11]/span[1]/span[1]"
    ADD_USER_MARKETLIST_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[14]/span[1]/span[1]"
    ADD_USER_ETRADOAPROVE_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[15]/span[1]/span[1]"
    ADD_USER_TAKANON_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[16]/span[1]/span[1]"
    ADD_USER_ADD_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/input[1]"
    ####################################################################################################################
    # trying to add by incorect requirments XPATH
    ADD_USER_ERROR_STOREID_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[8]/div[1]"
    ADD_USER_ERROR_EMAIL_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[4]/div[1]"
    ADD_USER_ERROR_PHONE_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[5]/div[1]"
    ADD_USER_ERROR_PHONE2_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[6]/div[1]"
    ADD_USER_ERROR_STOREID_XPATH = "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[8]/div[1]"
    ####################################################################################################################





