class Locators_Dep:
    Title =  "מחלקות - trado"
    DEPARTMENT_XPATH= "//body/div[@id='root']/div[1]/div[2]/div[1]/nav[1]/div[2]/a[20]"
    CHOOSE = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[1]/span[1]/i[1]"
    ADD_PRODUCT = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/span[1]/i[1]"
    EXPORT_PRODUCT= "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/span[1]/i[1]"
    TITLE = "//h4[contains(text(),'דשבורד')]"
    DASHBOARD="//body/div[@id='root']/div[1]/div[2]/main[1]/div[1]/div[1]/span[1]/span[1]/i[1]"
    NAME="/html/body/div/div[1]/div[2]/main/div[2]/div/div[2]/div[1]/table/thead/tr/th[2]/text()"
    SEARCH_BOX_XPATH = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/span[1]/span[1]/div[1]/input[1]"
    ADD_COUNT="//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]"
    TOTAL_PRODUCTS="/html/body/div/div[1]/div[2]/main/div[2]/div/div[2]/div[2]/div[2]"
    DROP_ICON = "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/span[1]"
    LIST_NUM = "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/span[1]/div[2]/div[1]/div[3]"
    ADD_Count="//div[contains(text(),'100')]"
    ON__OFF="//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[4]/span[1]/span[1]"
    X_BUTTON="//body/div[@id='root']/div[1]/div[4]/div[1]/span[1]/i[1]"
    DEPARTMENT_NAME="//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[1]/span[1]/div[1]/input[1]"
    Department_Input="//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[1]/span[1]/div[1]/input[1]"
    DEPARTMENT_1="//span[contains(text(),'מחלקה')]"
    EXPORT_NAME="//span[contains(text(),'ייצוא')]"
    Add_Name="//span[contains(text(),'הוספה')]"
    # test
